apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway-full.fullname" . }}
  labels:
    {{- include "api-gateway-full.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api-gateway-full.selectorLabels" . | nindent 4 }}
