apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-full
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <your-git-repo-url>
    targetRevision: HEAD
    path: helm-charts/api-gateway-full
    helm:
      valueFiles:
        - ../../../values/api-gateway-full.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: api-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
